
export const genreMap_ES_EN = {
    "Comedia": "Comedy",
    "Acción": "Action",
    "Drama": "Drama",
    "Animación": "Animation",
    "Cine de autor": "Art Cinema",
    "Film Noir": "Film Noir",
    "Familiar": "Family",
    "Deportes": "Sports",
    "Histórica": "Historical",
    "Biografía": "Biography",
    "Thriller": "Thriller",
    "Suspense": "Suspense",
    "Musical": "Music",
    "Western": "Western",
    "Documental": "Documentary",
    "Guerra": "War",
    "Romance": "Romance",
    "Misterio": "Mystery",
    "Fantasía": "Fantasy",
    "Aventura": "Adventure",
    "Crimen": "Crime",
    "Ciencia Ficción": "Science Fiction",
    "Terror": "Horror",
}

export const genreMap_EN_ES = {
    "Comedy": "Comedia",
    "Action": "Acción",
    "Drama": "Drama",
    "Animation": "Animación",
    "Art Cinema": "Cine de autor",
    "Film Noir": "Film Noir",
    "Family": "Familiar",
    "Sports": "Deportes",
    "Historical": "Histórica",
    "Biography": "Biografía",
    "Thriller": "Thriller",
    "Suspense": "Suspense",
    "Music": "Musical",
    "Western": "Western",
    "Documentary": "Documental",
    "War": "Guerra",
    "Romance": "Romance",
    "Mystery": "Misterio",
    "Fantasy": "Fantasía",
    "Adventure": "Aventura",
    "Crime": "Crimen",
    "Science Fiction": "Ciencia Ficción",
    "Horror": "Terror",
}